version: '3.8'

services:
  database:
    image: mysql:8.0.33
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testting
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456" ]
      interval: 30s
      retries: 10
      timeout: 20s

  springboot-app:
    image: duytanpn/springboot-app:latest
    build: .
    container_name: springboot-app
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8088:8088"
    env_file: 
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/testting
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8088
      SERVER_SERVLET_CONTEXT_PATH: /test
    restart: on-failure
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-data: