
server:
  port: 8088
  servlet:
    context-path: /test
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_HOST}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  payment:
    tpbank:
      account-number: TPBANK_ACCOUNT_NUMBER
      bank-code: 970423
    qr:
      base-url: https://img.vietqr.io/image
  cloudinary:
    cloud_name: ${CLOUDINARY_CLOUD_NAME}
    api_key: ${CLOUDINARY_API_KEY}
    api_secret: ${CLOUDINARY_API_SECRET}

  mail:
    host: smtp.gmail.com
    port: 587
    username: zkp.hades@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  auth:
    app: ShoesShop
    secret_key: ${JWT_KEY}
    expires_in: 86400
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true